### ISSUE TITLE
Nucleus vanish

### ISSUE THREAD

**Issue by Heriptik** [Pixelmon-Development/Pixelmon-Mixins#4]
Hi, i use nucleus 1.14.7-S7.1, latest PixelmonFixes Jar.

Player nucleus vanished do not spawn pokemon (this is normal), if player disable the vanish Pokémon still do not spawn on the player.

If I remove the jar it works perfectly again

**Comment by vaniron** [comment]
it's an issue between Pixelmon & Sponge and will not be fixed but you can just relog after disabling the vanish to make pokémon spawn around you again

**Comment by Heriptik** [comment]
Okay, but why your jar breaks the nucleus vanish ?

**Comment by vaniron** [comment]
Its not my plugin, I just forwarded the reply from the mixins author as he wrote on discord 2 days ago:
"Yeah it's potentially a sponge issue but basically what I did is changed the pokemon despawning code to redirect to a more general entity despawning code (was the same thing already). Sponge changes this despawning code
So it's an issue between Pixelmon & Sponge basically
Not worth down grading because of as it only affects people with access to vanish"

So you will have to wait for his response but i dont think he will change the decision anyway.

**Comment by SrT3ddy** [comment]
I have the same problem

**Comment by danorris709** [comment]
Like I said on Discord it's an issue that occurs between Pixelmon and Sponge (when using Sponge's despawning algorithm). As it only happens to vanished players it's not something I'm looking to spend time on fixing.
